In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import tensorflow

In [2]:
df_Data_set=pd.read_csv("DataSet.csv")

In [3]:
df_Label_set=pd.read_csv("LabelSet.csv")

In [4]:
df_Data_set

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,18,19,20,21,22,23,24,25,26,27
0,0,0.86929,-0.63508,0.22569,0.32747,-0.68999,0.75420,-0.24857,-1.09206,0.00000,...,-0.01045,-0.04577,3.10196,1.35376,0.97956,0.97808,0.92000,0.72166,0.98875,0.87668
1,1,0.90754,0.32915,0.35941,1.49797,-0.31301,1.09553,-0.55752,-1.58823,2.17308,...,-1.13893,-0.00082,0.00000,0.30222,0.83305,0.98570,0.97810,0.77973,0.99236,0.79834
2,2,0.79883,1.47064,-1.63597,0.45377,0.42563,1.10487,1.28232,1.38166,0.00000,...,1.12885,0.90046,0.00000,0.90975,1.10833,0.98569,0.95133,0.80325,0.86592,0.78012
3,3,1.34438,-0.87663,0.93591,1.99205,0.88245,1.78607,-1.64678,-0.94238,0.00000,...,-0.67838,-1.36036,0.00000,0.94665,1.02870,0.99866,0.72828,0.86920,1.02674,0.95790
4,4,1.10501,0.32136,1.52240,0.88281,-1.20535,0.68147,-1.07046,-0.92187,0.00000,...,-0.37357,0.11304,0.00000,0.75586,1.36106,0.98661,0.83808,1.13330,0.87224,0.80849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10999995,10999995,1.15991,1.01385,0.10861,1.49552,-0.53754,2.34240,-0.83974,1.32068,0.00000,...,-0.09707,1.19068,3.10196,0.82214,0.76677,1.00219,1.06123,0.83700,0.86047,0.77248
10999996,10999996,0.61839,-1.01298,1.11014,0.94102,-0.37920,1.00466,0.34854,-1.67859,2.17308,...,-0.21699,1.04918,3.10196,0.82683,0.98981,1.02910,1.19968,0.89148,0.93849,0.86527
10999997,10999997,0.70056,0.77425,1.52018,0.84711,0.21123,1.09553,0.05246,0.02455,2.17308,...,1.58523,1.71396,0.00000,0.33737,0.84521,0.98761,0.88342,1.88844,1.15377,0.93128
10999998,10999998,1.17803,0.11780,-1.27698,1.86446,-0.58437,0.99852,-1.26455,1.27633,0.00000,...,1.39952,-1.31319,0.00000,0.83884,0.88289,1.20138,0.93922,0.33970,0.75907,0.71912
10999999,10999999,0.46448,-0.33705,0.22902,0.95460,-0.86847,0.43000,-0.27135,-1.25228,2.17308,...,-1.65278,-0.58625,0.00000,0.75253,0.74073,0.98692,0.66395,0.57608,0.54143,0.51742

In [5]:
Data_set=np.array(df_Data_set.iloc[:,1:])

In [6]:
Label_set=np.array(df_Label_set.iloc[:,1:])

In [7]:
normed_df_Data_set = ((df_Data_set - df_Data_set.min()) / (df_Data_set.max() - df_Data_set.min())).astype(np.float32)
normed_df_Data_set

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,18,19,20,21,22,23,24,25,26,27
0,0.000000e+00,0.050286,0.369601,0.564642,0.021253,0.302234,0.062910,0.458154,0.186402,0.0,...,0.497833,0.486773,1.0,0.031874,0.038707,0.113156,0.055765,0.038036,0.061924,0.067874
1,9.090910e-08,0.053521,0.567601,0.603004,0.097277,0.410338,0.097729,0.406137,0.043934,1.0,...,0.271923,0.499667,0.0,0.005662,0.031445,0.114120,0.059877,0.041314,0.062247,0.058134
2,1.818182e-07,0.044327,0.802000,0.030564,0.029457,0.622152,0.098682,0.715906,0.896692,0.0,...,0.725909,0.758206,0.0,0.020806,0.045090,0.114118,0.057983,0.042641,0.050959,0.055869
3,2.727273e-07,0.090465,0.320000,0.768391,0.129367,0.753152,0.168172,0.222741,0.229380,0.0,...,0.364120,0.109674,0.0,0.021726,0.041143,0.115758,0.042198,0.046364,0.065316,0.077971
4,3.636364e-07,0.070221,0.566001,0.936645,0.057322,0.154448,0.055491,0.319775,0.235269,0.0,...,0.425140,0.532329,0.0,0.016970,0.057617,0.114235,0.049968,0.061272,0.051523,0.059396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10999995,9.999996e-01,0.074864,0.708200,0.531054,0.097118,0.345951,0.224923,0.358620,0.879182,0.0,...,0.480493,0.841457,1.0,0.018622,0.028159,0.116204,0.065760,0.044546,0.050472,0.054919
10999996,9.999997e-01,0.029067,0.292001,0.818375,0.061103,0.391357,0.088460,0.558688,0.017989,1.0,...,0.456486,0.800867,1.0,0.018739,0.039215,0.119606,0.075558,0.047622,0.057437,0.066455
10999997,9.999998e-01,0.036016,0.659000,0.936008,0.055004,0.560670,0.097729,0.508838,0.507019,1.0,...,0.817271,0.991564,0.0,0.006538,0.032048,0.114361,0.053177,0.103900,0.076656,0.074661
10999998,9.999999e-01,0.076397,0.524201,0.133552,0.121080,0.332522,0.087833,0.287096,0.866448,0.0,...,0.780094,0.123205,0.0,0.019038,0.033915,0.141387,0.057126,0.016474,0.041420,0.048286
10999999,1.000000e+00,0.016050,0.430800,0.565597,0.061985,0.251052,0.029838,0.454319,0.140397,1.0,...,0.169056,0.331733,0.0,0.016887,0.026869,0.114274,0.037645,0.029818,0.021990,0.023210

In [8]:
df_normed_Data_set=pd.DataFrame(np.array(normed_df_Data_set.iloc[:,1:]))

In [9]:
df_normed_Data_set.to_csv("DataSetNormalised.csv")